(() => {
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const map = q => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
  const addLink = (rel, href) => { if (!$(`link[rel="${rel}"]`)) { const l=document.createElement('link'); l.rel=rel; l.href=href; document.head.appendChild(l); } };
  addLink('stylesheet','enhancements.css?v=20260906');
  addLink('manifest','manifest.webmanifest');
  if (!$('meta[name="theme-color"]')) { const m=document.createElement('meta'); m.name='theme-color'; m.content='#713233'; document.head.appendChild(m); }

  const nav=$('.nav-links');
  if(nav && !$('a[href="#travel-mode"]',nav)){const a=document.createElement('a');a.href='#travel-mode';a.textContent='旅行模式';nav.prepend(a);}
  const hero=$('.hero-content');
  if(hero && !$('.hero-stats',hero)){
    const sub=$('.hero-subtitle',hero); if(sub) sub.textContent='三城住宿已订：罗马 Le Méridien Visconti、佛罗伦萨 La Casa del Garbo、威尼斯 voco Mestre。旅行当天打开就能看今天、下一站、时间、导航和附近吃什么。';
    const actions=$('.hero-actions',hero); if(actions){const first=$('a',actions);if(first){first.href='#travel-mode';first.textContent='打开旅行模式';} if(!$('a[href="#food"]',actions)){const a=document.createElement('a');a.className='btn secondary';a.href='#food';a.textContent='附近吃什么';actions.insertBefore(a,actions.lastElementChild);}}
    hero.insertAdjacentHTML('beforeend','<div class="hero-stats"><div><strong>10</strong><span>旅行日</span></div><div><strong>3</strong><span>城市</span></div><div><strong>8</strong><span>住宿晚</span></div><div><strong>3</strong><span>酒店已订</span></div></div>');
  }
  if(!$('#travel-mode')) $('header.hero')?.insertAdjacentHTML('afterend',`<section class="travel-mode-shell" id="travel-mode"><div class="travel-mode-card"><div class="travel-mode-main"><p class="eyebrow">Travel Mode · Europe/Rome</p><div class="travel-mode-topline"><span id="tm-date">读取日期…</span><span class="live-dot">LIVE</span></div><h2 id="tm-title">下一站：意大利</h2><p id="tm-next">正在整理下一项行程…</p><div class="travel-progress"><span id="tm-bar"></span></div><div class="travel-mode-actions"><a class="quick-btn primary-mini" id="tm-today" href="#itinerary">查看当天</a><a class="quick-btn" href="#booking">预约</a><a class="quick-btn" href="#food">吃什么</a></div></div><aside class="travel-mode-side"><span class="side-label">旅行中最常用</span><a href="${map('Vatican City')}" target="_blank" rel="noopener"><b>地图</b><small>景点导航</small></a><a href="https://www.trenitalia.com/en.html" target="_blank" rel="noopener"><b>高铁</b><small>Trenitalia</small></a><a href="https://www.veneziaunica.it/en" target="_blank" rel="noopener"><b>水巴</b><small>Venezia Unica</small></a></aside></div></section>`);

  const days=[
    ['2026-09-27','D1','9/27 周日 · Rome','香港 → 罗马｜抵达夜','不安排不可取消项目，给长途飞行留缓冲。',[['08:55','香港 HKG 起飞','土耳其航空，经伊斯坦布尔转机'],['18:25','抵达 Rome FCO','入境、取行李后直接进城','Fiumicino Airport'],['20:15','入住 Le Méridien Visconti Rome','长途抵达夜只在 Prati / 酒店附近吃','Le Meridien Visconti Rome'],['21:15','可选夜散步','有体力再去纳沃纳广场 / 万神殿外观']]],
    ['2026-09-28','D2','9/28 周一 · Rome','圣彼得 + 梵蒂冈博物馆','重点保留体力给 14:30 已预约的梵蒂冈博物馆。',[['07:30','抵达圣彼得广场','尽早安检；穹顶排队过长就放弃',"St Peter's Basilica"],['08:00–10:30','圣彼得大教堂','主殿 + 可选穹顶'],['11:15','圣天使堡外观 + 台伯河','轻松散步，不再塞大型景点'],['12:00','平价午餐 · Borgo / Prati','Pastasciutta 或 Pinsa ’Mpò','food'],['14:30','梵蒂冈博物馆 ✅ 已预约','14:00–14:15 抵达入口；西斯廷礼拜堂收尾','https://tickets.museivaticani.va/home','booked'],['19:00','梵蒂冈附近晚餐','就近吃，不再横穿老城']]],
    ['2026-09-29','D3','9/29 周二 · Rome','古罗马核心 + 万神殿晚餐','上午重景点，下午恢复，晚上再进入老城。',[['09:00','斗兽场','接古罗马广场 + 帕拉蒂尼山','https://ticketing.colosseo.it/en/','booked'],['13:00','Monti 午餐','吃完回酒店休息'],['17:00','卡比托利欧山 → 威尼斯广场','步行到万神殿和纳沃纳广场'],['20:00','Armando al Pantheon','正式罗马菜晚餐','Armando al Pantheon Rome','booked'],['22:00','特莱维喷泉夜景','饭后散步收尾']]],
    ['2026-09-30','D4','9/30 周三 · Rome → Florence','博尔盖塞 → 佛罗伦萨','上午最后一座美术馆，午后直达高铁。',[['07:30','退房 + 行李寄存','只带小包去美术馆'],['09:00–11:00','博尔盖塞美术馆','贝尔尼尼、卡拉瓦乔、拉斐尔、提香、卡诺瓦','Galleria Borghese Rome','booked'],['11:30','轻午餐 + 取行李','不要吃太正式'],['13:20–14:20','Roma Termini → Firenze SMN','只选直达高铁；以最终车票为准','https://www.trenitalia.com/en.html'],['16:00','入住 La Casa del Garbo','Piazza della Signoria','La Casa del Garbo Florence','booked'],['17:00','大教堂外观 → 领主广场 → 老桥','第一晚慢慢进入佛罗伦萨'],['20:00','La Giostra','约会晚餐','La Giostra Florence']]],
    ['2026-10-01','D5','10/1 周四 · Florence','乌菲兹 + Oltrarno','上午重磅美术馆，下午慢逛。',[['09:00','乌菲兹美术馆','文艺复兴核心作品','https://www.uffizi.it/en/tickets','booked'],['12:30','平价午餐','Il Cernacchio / Il Bufalo Trippone','food'],['15:30','Santo Spirito + Oltrarno','老桥、阿诺河慢逛'],['20:00','正式晚餐','Buca Lapi / B-Roof / Borgo San Jacopo，按最终预约','food']]],
    ['2026-10-02','D6','10/2 周五 · Florence → Mestre / Venice','入住 voco → 轻装进岛','行李先放 Mestre，下午再进入威尼斯。',[['10:00–10:40','Firenze SMN → Venezia Mestre','终点不要买到 Santa Lucia','https://www.trenitalia.com/en.html'],['12:30','入住 voco Venice Mestre','放行李、短休息','voco Venice Mestre The Quid','booked'],['14:30','从 Mestre 进岛','目标 Santa Lucia / Piazzale Roma'],['15:00','平价 Bacaro','Bacareto da Lele / Bacaro Quebrado','food'],['16:00','Cannaregio → Rialto → 圣马可','第一晚以散步为主'],['20:00','Cicchetti + 返 Mestre','别拖到太晚']]],
    ['2026-10-03','D7','10/3 周六 · Mestre → Venice','圣马可 + 总督宫 + 贡多拉','整天留在岛上，不往返酒店午休。',[['07:30','从 voco 出发进岛','预留通勤缓冲'],['09:00–10:00','圣马可大教堂','按最终门票时间','Basilica di San Marco Venice','booked'],['10:15–12:30','总督宫','叹息桥、宫殿核心路线','Doge Palace Venice','booked'],['13:00','岛上午餐 + 咖啡休息','不回 Mestre'],['15:00','Dorsoduro → 学院桥 → Salute','慢走'],['18:30','贡多拉','日落前后体验'],['19:30','Antiche Carampane / Al Covo','吃完直接返 Mestre','food']]],
    ['2026-10-04','D8','10/4 周日 · Mestre / Burano','Burano 慢游','避免一天硬塞三岛。',[['07:45','从 voco 出发进岛','早进岛'],['09:00','Fondamente Nove 转水巴','去 Burano'],['09:30','Burano 彩色岛慢逛','拍照、运河散步'],['12:30','Al Gatto Nero','告别正式午餐','Al Gatto Nero Burano','booked'],['15:00','回主岛或 Mestre','有体力再做最后一次运河散步'],['19:00','轻晚餐 + 整理行李','早睡，为清晨航班准备']]],
    ['2026-10-05','D9','10/5 周一 · Mestre','陆路去 VCE → 香港','不用水上出租车。',[['05:30','voco 退房 + 陆路接送','提前请酒店约出租车 / 接送','booked'],['06:30','抵达 Marco Polo Airport','留足值机和安检时间','Venice Marco Polo Airport'],['09:20','VCE 起飞','经伊斯坦布尔返港']]],
    ['2026-10-06','D10','10/6 周二 · Hong Kong','抵港 → 深圳','旅程收尾。',[['07:40','预计抵达 HKG','以航司实际为准'],['09:30','衔接回深圳','跨境车 / 巴士 / 高铁']]]
  ];
  const action=(x)=>{if(!x)return'';if(x==='food')return'<a class="row-action" href="#food">吃什么</a>';const href=x.startsWith('http')?x:map(x);return `<a class="row-action" href="${href}" target="_blank" rel="noopener">${x.startsWith('http')?'打开':'导航'}</a>`};
  const itinerary=$('#itinerary'); if(itinerary){itinerary.innerHTML=`<div class="section-heading"><p class="eyebrow">Daily Itinerary</p><h2>按小时展开的每日行程</h2><p>旅行当天会自动高亮“今天”。手机上先看时间，再点导航、票务或吃什么。</p></div><div class="timeline-v2">${days.map(d=>`<article class="day-card" id="day-${d[0]}" data-date="${d[0]}"><header><div><span class="day-number">${d[1]}</span><time>${d[2]}</time></div><h3>${d[3]}</h3><p>${d[4]}</p></header><div class="hour-list">${d[5].map(e=>`<div class="hour-row ${e[4]||''}"><span class="hour">${e[0]}</span><div><b>${e[1]}</b><small>${e[2]}</small></div>${action(e[3])}</div>`).join('')}</div></article>`).join('')}</div>`;}

  const foods=[
    ['budget nearby rome','ROME · Vatican','€','Pastasciutta Roma','Via delle Grazie 5，梵蒂冈旁。现做意面，适合 9/28 午餐；无需专门订位。','Pastasciutta Roma','https://pastasciuttaroma.it/'],
    ['budget nearby rome','ROME · Prati','€','Pinsa ’Mpò','Via dei Gracchi 7。Roman pinsa，适合快速轻午餐。',"Pinsa m'po Rome",''],
    ['date rome','ROME · 9/29','♥','Armando al Pantheon','传统罗马菜正式晚餐，万神殿旁。','Armando al Pantheon Rome','https://armandoalpantheon.it/prenota/'],
    ['budget nearby florence','FLORENCE · Signoria','€','Il Cernacchio','Via della Condotta 38R，离领主广场很近；有 Schiacciata 和热食。','Il Cernacchio Florence','https://www.ilcernacchio.com/'],
    ['budget florence','FLORENCE · Santa Croce','€','Il Bufalo Trippone','Via dell’Anguillara 48R。Schiacciata、火腿奶酪，适合 10/1 平价午餐。','Il Bufalo Trippone Florence','https://www.ilbufalotrippone.com/'],
    ['date florence','FLORENCE · 9/30','♥','La Giostra','佛罗伦萨第一晚的氛围约会餐。','La Giostra Florence','https://ristorantelagiostra.com/'],
    ['date florence','FLORENCE · 10/1','♥','Buca Lapi','两人共享佛罗伦萨牛排，再配前菜和蔬菜。','Buca Lapi Florence','https://www.bucalapi.com/en/'],
    ['date florence','FLORENCE · 景观备选','♥','B-Roof Restaurant','想把晚餐做成屋顶景观夜，建议约 20:00。','B-Roof Restaurant Florence','https://b-roof.myrestoo.net/en/reservar'],
    ['date florence','FLORENCE · 河景备选','♥','Borgo San Jacopo','阿诺河景正式晚餐，适合最后一晚升级。','Borgo San Jacopo Florence','https://www.sevenrooms.com/explore/borgosanjacopo/reservations/create/search/landing'],
    ['budget nearby venice','VENICE · 10/2','€','Bacareto da Lele','靠近 Piazzale Roma，小 Paninetti + Ombra；周日休息，所以放周五抵达日。','Bacareto da Lele Venice',''],
    ['budget nearby venice','VENICE · Santa Lucia','€','Bacaro Quebrado','Cicchetti 之外还有热食，适合想吃饱一点又不想正式海鲜餐。','Bacaro Quebrado Venice','https://bacaroquebrado.it/en'],
    ['budget venice','VENICE · Cannaregio','€€','Cantina Aziende Agricole','Baccalà、Sarde in saor、Pasta 和酒都有。','Cantina Aziende Agricole Venice','https://www.cantinaaziendeagricole.com/'],
    ['date venice','VENICE · 10/3','♥','Antiche Carampane / Al Covo','正式海鲜晚餐二选一；住 Mestre，建议 19:00–19:30 开餐。','Antiche Carampane Venice','https://booking.resdiary.com/widget/Standard/AnticheCarampane/6454'],
    ['date venice','BURANO · 10/4','♥','Al Gatto Nero da Ruggero','把正式餐放在 Burano 午餐，下午自由回主岛或 Mestre。','Al Gatto Nero Burano','mailto:info@gattonero.com']
  ];
  const food=$('#food'); if(food){food.innerHTML=`<div class="section-heading"><p class="eyebrow">Eat Smart</p><h2>约会餐 + 平价美食</h2><p>不是每顿都吃贵的：正式餐保留仪式感，其余优先顺路、快、当地化。</p></div><div class="food-toolbar"><button class="food-filter active" data-filter="all">全部</button><button class="food-filter" data-filter="nearby">📍 顺路</button><button class="food-filter" data-filter="budget">€ 平价</button><button class="food-filter" data-filter="date">♥ 约会餐</button><button class="food-filter" data-filter="rome">Rome</button><button class="food-filter" data-filter="florence">Florence</button><button class="food-filter" data-filter="venice">Venice</button></div><div class="food-smart-grid">${foods.map(f=>`<article class="food-smart-card ${f[0].includes('budget')?'budget':'date'}" data-tags="${f[0]}"><div class="food-meta"><span>${f[1]}</span><i>${f[2]}</i></div><h3>${f[3]}</h3><p>${f[4]}</p><div class="food-actions"><a href="${map(f[5])}" target="_blank" rel="noopener">地图</a>${f[6]?`<a href="${f[6]}" target="_blank" rel="noopener">${f[6].startsWith('mailto:')?'邮件':'官网/订位'}</a>`:''}</div></article>`).join('')}</div><div class="food-tip"><strong>旅行时怎么用：</strong>饿了先点 <b>📍 顺路</b>；控预算点 <b>€ 平价</b>；正式晚餐只看 <b>♥ 约会餐</b>。</div>`;}

  const ch=$('#checklist .section-heading'); if(ch&&!$('.check-progress',ch))ch.insertAdjacentHTML('beforeend','<div class="check-progress"><span id="cp-label">0 / 0 已完成</span><div><i id="cp-bar"></i></div></div>');
  if(!$('.bottom-nav')) $('.footer')?.insertAdjacentHTML('beforebegin','<nav class="bottom-nav"><a href="#travel-mode"><span>◉</span><b>今天</b></a><a href="#itinerary"><span>⌚</span><b>行程</b></a><a href="#booking"><span>✓</span><b>预订</b></a><a href="#food"><span>♨</span><b>吃什么</b></a></nav>');
  const ft=$('.footer p');if(ft)ft.textContent='Made for your Italy trip · Travel Mode UI · 最后更新 2026.09.06 · 三城住宿已订';
  const boxes=$$('.checklist input'),cpL=$('#cp-label'),cpB=$('#cp-bar');const cp=()=>{const n=boxes.filter(x=>x.checked).length;if(cpL)cpL.textContent=`${n} / ${boxes.length} 已完成`;if(cpB)cpB.style.width=`${boxes.length?n/boxes.length*100:0}%`};boxes.forEach(x=>x.addEventListener('change',cp));cp();
  $$('.food-filter').forEach(btn=>btn.addEventListener('click',()=>{const f=btn.dataset.filter;$$('.food-filter').forEach(b=>b.classList.toggle('active',b===btn));$$('.food-smart-card').forEach(c=>c.classList.toggle('is-hidden',f!=='all'&&!(c.dataset.tags||'').split(/\s+/).includes(f)));}));

  const plan=days.map(d=>({date:d[0],city:d[2].split(' · ').pop(),title:d[3],events:d[5].map(e=>[e[0].slice(0,5),e[1]])}));
  const italyNow=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`}};
  const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};const diff=(a,b)=>Math.round((new Date(b+'T00:00:00Z')-new Date(a+'T00:00:00Z'))/86400000);
  function renderTM(){const n=italyNow(),de=$('#tm-date'),ti=$('#tm-title'),ne=$('#tm-next'),bar=$('#tm-bar'),go=$('#tm-today');$$('.day-card').forEach(c=>c.classList.toggle('current-day',c.dataset.date===n.date));if(n.date<'2026-09-27'){const left=diff(n.date,'2026-09-27');de.textContent=`出发前 · Italy time ${n.date}`;ti.textContent=`距离出发还有 ${left} 天`;ne.textContent='下一项：9/27 08:55 香港 HKG 起飞 → Rome FCO';bar.style.width='0%';go.textContent='查看 D1';go.href='#day-2026-09-27';return}if(n.date>'2026-10-06'){de.textContent='旅程已完成';ti.textContent='Italia 2026 · 完成';ne.textContent='把这份网站留作旅行回忆吧。';bar.style.width='100%';go.href='#itinerary';return}let i=plan.findIndex(d=>d.date===n.date);if(i<0)i=plan.findIndex(d=>d.date>n.date);const d=plan[i],cur=mins(n.time),ev=d.events.find(e=>mins(e[0])>=cur)||d.events.at(-1);de.textContent=`D${i+1} · ${d.date} · ${d.city}`;ti.textContent=d.title;ne.textContent=`下一项 ${ev[0]} · ${ev[1]}`;bar.style.width=`${Math.max(5,(i+1)/plan.length*100)}%`;go.textContent='查看今天';go.href=`#day-${d.date}`}
  renderTM();setInterval(renderTM,60000);
  if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();